import {library} from '@fortawesome/fontawesome-svg-core';
import {
    faBackward,
    faBowlFood,
    faBrain,
    faCheck,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faClock,
    faCubesStacked,
    faDog,
    faDrumstickBite,
    faFish,
    faForward,
    faHouse,
    faMoon,
    faPaw,
    faPlantWilt,
    faSailboat,
    faSeedling,
    faSkull,
    faTree,
    faUser,
    faWater,
    faWheatAwn
} from '@fortawesome/free-solid-svg-icons';

export const loadIcons = () => {
    library.add(
        faBackward,
        faBowlFood,
        faBrain,
        faCheck,
        faChevronDown,
        faChevronLeft,
        faChevronRight,
        faChevronUp,
        faClock,
        faCubesStacked,
        faDog,
        faDrumstickBite,
        faFish,
        faForward,
        faHouse,
        faMoon,
        faPaw,
        faPlantWilt,
        faSailboat,
        faSeedling,
        faSkull,
        faTree,
        faUser,
        faWater,
        faWheatAwn
    );
};